# Ruff configuration
# Exclude backup and archive directories from linting to keep Problems clean.
exclude = [
    ".git",
    "node_modules",
    ".venv",
    "venv",
    "env",
    "__pycache__",
    ".python-backups",
    ".markdown-backups",
    "archive",
]
