# UV Configuration for xanadOS Search & Destroy
# Minimal configuration for modern Python package management

# Basic settings
cache-dir = ".uv-cache"
index-url = "https://pypi.org/simple/"

# Project configuration goes in pyproject.toml
# UV-specific settings stay minimal here
