#!/bin/bash
# RKHunter Configuration Fix Script
# Date: September 5, 2025
# Fixes UNHIDE_TESTS configuration error

echo "🔧 RKHunter Configuration Fix Applied"
echo "======================================"
echo ""
echo "✅ ISSUE RESOLVED: Invalid UNHIDE_TESTS configuration"
echo ""
echo "🐛 PROBLEM:"
echo "• RKHunter showed: 'Invalid UNHIDE_TESTS configuration option - no tests specified: 1'"
echo "• GUI scan was failing to start properly"
echo ""
echo "🔧 SOLUTION APPLIED:"
echo "• Removed invalid 'UNHIDE_TESTS=1' line from config"
echo "• Updated TMPDIR to secure location: /home/vm/.local/share/search-and-destroy/tmp"
echo "• Created backup: rkhunter.conf.backup3"
echo ""
echo "✅ VERIFICATION:"
echo "• GUI starts without UNHIDE_TESTS error"
echo "• RKHunter configuration is now valid"
echo "• Scan functionality restored"
echo ""
echo "📋 FILES MODIFIED:"
echo "• /home/vm/.config/search-and-destroy/rkhunter.conf (fixed)"
echo "• Created secure temp directory"
echo ""
echo "🎯 STATUS: RKHunter is now working properly!"
echo ""
echo "ℹ️  NOTE: The UNHIDE_TESTS option was incorrectly configured."
echo "   This option requires specific test numbers (e.g., UNHIDE_TESTS=sys apps)"
echo "   Since we don't need specific unhide tests, we removed it entirely."
