name: Spellcheck

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Run cspell
        run: |
          npx cspell "**/*.md" --no-progress --no-summary \
            --exclude "node_modules/**" \
            --exclude "archive/**" \
            --exclude ".github/validation/**"
